

services:
  backend:
    build: ./backend
    container_name: mamb_kids_backend
    ports:
      - "3001:3001"
    # 💥 ESTA ES LA LÍNEA MÁGICA QUE FALTA:
    env_file:
      - .env
    restart: always
